spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/rss}
    username: ${DATASOURCE_USERNAME:rss}
    password: ${DATASOURCE_PASSWORD:rss}
  liquibase:
    enabled: true
    change-log: classpath:changelog/db.changelog-master.yaml
  elasticsearch:
    uris: localhost:9200
    connection-timeout: 1s

schedule:
  interval:
    period: 3600000
