name: deploy
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: oksi2233/news_agregator
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{steps.meta.outputs.tags}}
